### PR TITLE
Updating product tag for ms-identity-docs-code-dotnet

### PR DESCRIPTION
**Pull request by OwenRichards1**
## Purpose
Update product to Microsoft identity platform in order to be easy identifiable in code samples browser.
* ...

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
Update product to Microsoft identity platform.
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```
## What to Check
Verify that the following are valid
* ...
product tag  **ms-identity-platform**

### CODE REVIEW

**Comment by OwenRichards1** [comment]
@assign-reviewer: @mtrilbybassett

**Review by mtrilbybassett — CHANGES_REQUESTED** [review]
metadata value needs to be "microsoft-identity-platform" not "ms-identity-platform". That is not the valid slug https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main

**Comment by OwenRichards1** [comment]
> metadata value needs to be "microsoft-identity-platform" not "ms-identity-platform". That is not the valid slug https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main

Done!

**Review by mtrilbybassett — APPROVED** [review]
Looks good!

**Pull request merged**
